In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn. datasets import load_digits

In [2]:
digit=load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train,X_test,y_train,y_test=train_test_split(digit.data,digit.target,test_size=0.3)

### Logistic Regression

In [30]:
model= LogisticRegression(solver='liblinear',multi_class='ovr')
#solver='liblinear',multi_class='ovr'
model.fit(X_train,y_train)
model.score(X_train,y_train)*100

99.86091794158554

## Support vector Machine

In [31]:
svm=SVC(kernel='linear')
svm.fit(X_train,y_train)
svm.score(X_train,y_train)*100

100.0

## RandomForest Classifier

In [32]:
rf=RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)
rf.score(X_train,y_train)*100

100.0

# K fold

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=True)

In [7]:
kf

KFold(n_splits=5, random_state=True, shuffle=False)

In [57]:
for train_index,test_index in kf.split([0,1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


## Lets Create a model function

In [10]:
def get_model(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)*100

In [61]:
print('Accuracy score of Regression:',get_model(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
print('Accuracy score of SVM:',get_model(SVC(kernel='linear'),X_train,X_test,y_train,y_test))
print('Accuracy score of Random Forest:',get_model(RandomForestClassifier(n_estimators=100),X_train,X_test,y_train,y_test))

Accuracy score of Regression: 96.48148148148148
Accuracy score of SVM: 98.14814814814815
Accuracy score of Random Forest: 96.48148148148148


### Now apply the same method using KFold

In [63]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=4)

In [67]:
for train_index,test_index in folds.split([0,1,2,3,4,5,6,7,8,9],[10,10,10,10,10,20,20,20,20,20]):
    print(train_index,test_index)

[2 3 4 7 8 9] [0 1 5 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 3 5 6 7 8] [4 9]


In [68]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)

In [87]:
for train_index,test_index in skf.split(X,y):
    print(train_index,test_index)
X_train, X_test = X[train_index], X[test_index]
print(X_train)

[1 3] [0 2]
[0 2] [1 3]
[[1 2]
 [1 2]]


In [97]:
for test_index,train_index in skf.split([10,20,30,40,4,5,6,4],[1,2,1,2,1,1,1,1]):
    print(test_index,train_index)
#X_train, X_test = X[train_index], X[test_index]
print(train_index)
print(test_index)

[3 5 6 7] [0 1 2 4]
[0 1 2 4] [3 5 6 7]
[3 5 6 7]
[0 1 2 4]


In [86]:
train_index

array([0, 2])

In [8]:
kf

KFold(n_splits=5, random_state=True, shuffle=False)

In [22]:
scoreof_Logistic=[]
scoreof_SVM=[]
scoreof_rf=[]

for train_index,test_index in kf.split(digit.data):
    X_train,X_test,y_train,y_test= digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    #print(train_index,test_index)
    scoreof_Logistic.append(get_model(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    scoreof_SVM.append(get_model(SVC(kernel='linear'),X_train,X_test,y_train,y_test))
    scoreof_rf.append(get_model(RandomForestClassifier(n_estimators=100),X_train,X_test,y_train,y_test))

In [23]:
scoreof_Logistic

[93.05555555555556,
 88.61111111111111,
 95.26462395543176,
 95.82172701949861,
 89.69359331476323]

In [27]:
sum(scoreof_Logistic)/5

92.48932219127207

In [24]:
scoreof_SVM

[96.38888888888889,
 92.22222222222223,
 96.37883008356546,
 96.37883008356546,
 93.03621169916435]

In [25]:
scoreof_rf

[94.16666666666667,
 93.05555555555556,
 97.21448467966573,
 95.82172701949861,
 92.75766016713092]

## Magic of ML starts from here :-)

In [28]:
from sklearn.model_selection import cross_val_score

In [47]:
(cross_val_score(model,digit.data,digit.target,cv=5).sum()/5)*100

92.10188113360701

In [33]:
cross_val_score(svm,digit.data,digit.target,cv=5)

array([0.96428571, 0.92265193, 0.96657382, 0.96358543, 0.92957746])

In [35]:
cross_val_score(rf,digit.data,digit.target,cv=5)

array([0.93956044, 0.90055249, 0.96100279, 0.96918768, 0.92676056])